# Generated by Django 3.2 on 2022-09-16 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chocolates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='chocolates',
            options={'verbose_name_plural': 'Chocolates'},
        ),
    ]
