# Generated by Django 3.2 on 2022-09-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220917_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='chocolate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
