# Generated by Django 3.2 on 2022-09-19 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_complete'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChocolateItem',
            new_name='OrderItem',
        ),
        migrations.RenameModel(
            old_name='Address',
            new_name='SendingAddress',
        ),
    ]
