# Generated by Django 3.2 on 2022-09-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_chocolate_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='chocolate',
            name='description',
            field=models.TextField(default=False),
        ),
    ]
