# Generated by Django 3.2 on 2022-10-14 12:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_chocolate_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chocolate',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
