# Generated by Django 3.2 on 2022-10-17 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20221016_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='chocolate_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='chocolate',
            name='category',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
    ]
