# Generated by Django 3.2 on 2022-10-21 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20221017_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chocolate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
    ]
