# Generated by Django 3.2 on 2022-12-02 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0013_alter_chocolate_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendingaddress',
            name='buyer',
        ),
        migrations.AddField(
            model_name='sendingaddress',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
